import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

//! Update metadata to match your project
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full">
      <body className="flex flex-col h-full bg-light-gray">
        <header>
          <Navbar></Navbar>
        </header>
        {children}
      </body>
    </html>
  );
}
