import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import { UserRoleProvider } from "@/components/UserRoleProvider";

//! Update metadata to match your project
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "public/MTC_logo.png",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <UserRoleProvider>
        <html lang="en" className="h-full">
          <body className="flex flex-col h-full bg-light-gray">
            <header>
              <Navbar />
            </header>
            {children}
          </body>
        </html>
      </UserRoleProvider>
    </ClerkProvider>
  );
}
